spring:
  application:
    name: usermanagement
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: Adha@2005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: MonkeyD.LuffyWillFindOnePieceAndBecomeKingOfThePirates
  expiration: 3600000